const loanApplicationActions = {
  NEW_APPLICATION_REQUEST: "NEW_APPLICATION_REQUEST",
  NEW_APPLICATION_SUCCESS: "NEW_APPLICATION_SUCCESS",
  NEW_APPLICATION_FAILED: "NEW_APPLICATION_FAILED",
  GET_APPLICATION_REQUEST: "GET_APPLICATION_REQUEST",
  GET_APPLICATION_SUCCESS: "GET_APPLICATION_SUCCESS",
  GET_APPLICATION_FAILED: "GET_APPLICATION_FAILED",
};

export default loanApplicationActions;
